using System;using System.IO;using System.Collections.Generic;using System.Reflection;using System.Diagnostics;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine;
namespace StarRacingPrototype {
 [InitializeOnLoad] public static class F2DrivingDiagnostics {
  public static string Output=>Environment.GetEnvironmentVariable("STAR_RACING_F2_DIR");const string Key="StarRacing.F2Diagnostics";static int startup;static double began;
  static F2DrivingDiagnostics(){EditorApplication.playModeStateChanged+=Changed;}
  public static void Collision(){SessionState.SetBool(Key+"Collision",true);Angles();}
  public static void Angles(){Directory.CreateDirectory(Output);SessionState.SetBool(Key,true);SessionState.SetBool(Key+"Failed",false);EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);startup=0;EditorApplication.update+=Enter;}
  static void Enter(){if(++startup<15)return;EditorApplication.update-=Enter;EditorApplication.isPlaying=true;}
  static void Guard(){if(EditorApplication.timeSinceStartup-began>600)Fail(new Exception("F2 diagnostic timeout"));}
  static void Changed(PlayModeStateChange s){if(!SessionState.GetBool(Key,false))return;if(s==PlayModeStateChange.EnteredPlayMode){began=EditorApplication.timeSinceStartup;EditorApplication.update+=Guard;AudioListener.volume=0;Time.fixedDeltaTime=.01f;Time.maximumDeltaTime=.1f;Time.captureDeltaTime=.05f;if(SessionState.GetBool(Key+"Collision",false))new GameObject("F2 collision").AddComponent<F2CollisionDriver>();else new GameObject("F2 angle matrix").AddComponent<F2AngleDriver>();}if(s==PlayModeStateChange.EnteredEditMode){EditorApplication.update-=Guard;SessionState.SetBool(Key,false);SessionState.SetBool(Key+"Collision",false);EditorApplication.Exit(SessionState.GetBool(Key+"Failed",false)?1:0);}}
  public static void Fail(Exception e){UnityEngine.Debug.LogException(e);File.WriteAllText(Path.Combine(Output,"failure.txt"),e.ToString());SessionState.SetBool(Key+"Failed",true);EditorApplication.isPlaying=false;}
  [Serializable] public sealed class Cost {public int cars,ticks;public double projectionMs,vehicleMs,physicsMs,checkpointMs;public long allocatedBytes;public int accepted;}
  [Serializable] public sealed class CostReport {public List<Cost> cases=new List<Cost>();}
  public static void Costs(){bool allocationsOnly=Environment.GetEnvironmentVariable("STAR_RACING_F2_ALLOCATIONS_ONLY")=="1";Directory.CreateDirectory(Output);var mode=Physics.simulationMode;float dt=Time.fixedDeltaTime;var report=new CostReport();GameObject root=null;
   try{Physics.simulationMode=SimulationMode.Script;Time.fixedDeltaTime=.01f;root=new GameObject("F2 cost fixture");var road=new GameObject("road");road.transform.SetParent(root.transform);var track=road.AddComponent<TrackBuilder>();track.Build(new TrackRoute(Procedural.Generator.Generate(2273265884,"normal","cloud-city",true,true)));var balance=ReleaseBalance.Parse(Resources.Load<TextAsset>("balance-config").text);var tick=typeof(MagneticVehicle).GetMethod("FixedUpdate",BindingFlags.Instance|BindingFlags.NonPublic);
    foreach(int count in new[]{1,16,64}){var cars=new List<MagneticVehicle>();for(int i=0;i<count;i++){var obj=new GameObject("cost entrant");obj.transform.SetParent(root.transform);var car=obj.AddComponent<MagneticVehicle>();car.Initialize(track,i,Color.cyan,balance,true);car.ResetAt(80+(i/2)*6,i%2==0?-2.5f:2.5f);car.Body.linearVelocity=car.Frame.tangent*car.Drive.BaseSpeed;cars.Add(car);}Physics.SyncTransforms();
     void Step(int j,Cost c){long at=allocationsOnly?0:Stopwatch.GetTimestamp();foreach(var car in cars){car.PrepareProjection();car.SetRaceContext(true,1,count,j*.01);car.SetInput(new DrivingInput{throttle=1});}long next=allocationsOnly?0:Stopwatch.GetTimestamp();if(c!=null&&!allocationsOnly)c.projectionMs+=(next-at)*1000.0/Stopwatch.Frequency;at=next;foreach(var car in cars)tick.Invoke(car,null);next=allocationsOnly?0:Stopwatch.GetTimestamp();if(c!=null&&!allocationsOnly)c.vehicleMs+=(next-at)*1000.0/Stopwatch.Frequency;at=next;RacePhysicsStepper.Simulate(.01f);next=allocationsOnly?0:Stopwatch.GetTimestamp();if(c!=null&&!allocationsOnly)c.physicsMs+=(next-at)*1000.0/Stopwatch.Frequency;}
     for(int j=0;j<20;j++)Step(j,null);var cost=new Cost{cars=count,ticks=100};long allocation=GC.GetAllocatedBytesForCurrentThread();for(int j=20;j<120;j++)Step(j,cost);cost.allocatedBytes=GC.GetAllocatedBytesForCurrentThread()-allocation;
     var sample=track.Route.Evaluate(100);var watch=allocationsOnly?null:Stopwatch.StartNew();for(int j=0;j<100*count;j++)if(CheckpointAdmission.CheckPose(track,sample.position+sample.normal*VehicleGeometry.AdheredBodyHeight,sample.Rotation,100,VehicleGeometry.AdheredBodyHeight).accepted)cost.accepted++;if(watch!=null){watch.Stop();cost.checkpointMs=watch.Elapsed.TotalMilliseconds;}report.cases.Add(cost);UnityEngine.Debug.Log("F2_COST "+JsonUtility.ToJson(cost));foreach(var car in cars)UnityEngine.Object.DestroyImmediate(car.gameObject);
    }
    File.WriteAllText(Path.Combine(Output,"costs.json"),JsonUtility.ToJson(report,true));UnityEngine.Debug.Log("F2_COST_COLLECTION_OK");
   }finally{if(root!=null)UnityEngine.Object.DestroyImmediate(root);Physics.simulationMode=mode;Time.fixedDeltaTime=dt;}
  }
 }
 [Serializable] public sealed class F2AngleCase {public int index;public string jump,outcome,theme;public float offset;public float angle,initialSpeed,takeoffAlong,takeoffLateral,headingAtLaunch,flightSeconds,peak,maxSpeed,maxAlong,capImpulse,endLateral;public bool velocityAlongRoad,nitro;public long airSteps;}
 [Serializable] public sealed class F2AngleReport {public List<F2AngleCase> cases=new List<F2AngleCase>();}
 [DefaultExecutionOrder(-100)] public sealed class F2AngleDriver:MonoBehaviour {
  TrackBuilder track;GameObject root;MagneticVehicle car;Procedural.Jump jump;F2AngleCase result;F2AngleReport report=new F2AngleReport();int scenario,ticks,flight,stable,revision;bool launched;bool contract=>Environment.GetEnvironmentVariable("STAR_RACING_F2_CONTRACT")=="1";
  void Start(){try{gameObject.AddComponent<RacePhysicsStepper>();root=new GameObject("F2 road");track=root.AddComponent<TrackBuilder>();track.Build(new TrackRoute(Procedural.Generator.Generate(2273265884,"normal","cloud-city",true,true)));Setup();}catch(Exception e){F2DrivingDiagnostics.Fail(e);}}
  void Setup(){int angle=scenario%5;int ramp=(scenario/5)%2;bool nitro=(scenario/10)%2==1,along=scenario/20==1;string theme="cloud-city";float offset=0;float yaw=new[]{0f,1,-1,3,-3}[angle];if(contract){angle=scenario%2;ramp=(scenario/2)%4;nitro=(scenario/8)%2==1;offset=(scenario/16)%2==0?-.25f:.25f;theme=scenario/32==0?"cloud-city":"space-station";along=false;yaw=angle==0?1:-1;if(scenario==32){UnityEngine.Object.DestroyImmediate(root);root=new GameObject("F2 road space");track=root.AddComponent<TrackBuilder>();track.Build(new TrackRoute(Procedural.Generator.Generate(2273265884,"normal",theme,true,true)));}}var balance=ReleaseBalance.Parse(Resources.Load<TextAsset>("balance-config").text);jump=track.Route.Definition.jumps[ramp];float distance=30+jump.rampStartIndex*5-10;var obj=new GameObject("F2 entrant");car=obj.AddComponent<MagneticVehicle>();car.Initialize(track,0,Color.cyan,balance,true);car.ResetAt(distance,-(float)jump.lateralCenter+offset);var rotation=Quaternion.AngleAxis(yaw,car.Frame.normal)*car.Frame.Rotation;car.Body.rotation=rotation;car.transform.rotation=rotation;car.ResetPresentation();float speed=nitro?car.Drive.NitroSpeed:car.Drive.BaseSpeed;car.Body.linearVelocity=(along?car.Frame.tangent:rotation*Vector3.forward)*speed;Physics.SyncTransforms();result=new F2AngleCase{index=scenario,jump=jump.id,theme=theme,offset=offset,angle=yaw,initialSpeed=speed,velocityAlongRoad=along,nitro=nitro};ticks=flight=stable=0;launched=false;revision=car.PositionRevision;car.ContactObserved+=c=>{if(!launched&&c.collider.name==RoadVolumeMesh.SupportName)result.capImpulse=Mathf.Max(result.capImpulse,c.impulse.magnitude);};}
  void FixedUpdate(){try{if(car==null)return;car.PrepareProjection();car.SetRaceContext(true,1,1,ticks*.01);float steer=0;if(Environment.GetEnvironmentVariable("STAR_RACING_F2_CORRECTION")=="1"&&car.ActiveJumpId!=""&&flight>=10){float yaw=Vector3.SignedAngle(car.Frame.tangent,Vector3.ProjectOnPlane(car.Body.linearVelocity,car.Frame.normal),car.Frame.normal);float target=jump.kind=="partial"?-2:0;steer=-Mathf.Clamp((yaw-target)*.5f,-1,1);}car.SetInput(new DrivingInput{throttle=1,nitro=result.nitro,steer=steer});car.Hold(false);ticks++;result.maxSpeed=Mathf.Max(result.maxSpeed,car.Body.linearVelocity.magnitude);result.maxAlong=Mathf.Max(result.maxAlong,Vector3.Dot(car.Body.linearVelocity,car.Frame.tangent));
    if(car.ActiveJumpId!=""){if(!launched){launched=true;result.takeoffAlong=Vector3.Dot(car.Body.linearVelocity,car.Frame.tangent);result.takeoffLateral=Vector3.Dot(car.Body.linearVelocity,car.Frame.right);result.headingAtLaunch=Vector3.SignedAngle(car.Frame.tangent,Vector3.ProjectOnPlane(car.Body.rotation*Vector3.forward,car.Frame.normal),car.Frame.normal);}flight++;result.peak=Mathf.Max(result.peak,Vector3.Dot(car.Body.position-car.Frame.position,car.Frame.normal));}
    if(launched&&car.ActiveJumpId==""&&car.HandlingSupportCount>=3&&car.Distance>30+jump.gapEndIndex*5)stable++;else stable=0;
    if(stable>=20)Complete("landed");else if(car.IsFalling||car.PositionRevision!=revision)Complete("fall-or-recovery");else if(ticks>=500)Complete("timeout");
   }catch(Exception e){F2DrivingDiagnostics.Fail(e);}}
  void Complete(string why){result.outcome=why;result.airSteps=car.AirSteeringSteps;result.flightSeconds=flight*.01f;result.endLateral=Vector3.Dot(car.Body.position-car.Frame.position,car.Frame.right);report.cases.Add(result);UnityEngine.Debug.Log("F2_ANGLE "+JsonUtility.ToJson(result));UnityEngine.Object.DestroyImmediate(car.gameObject);car=null;if(contract&&why!="landed")throw new Exception("Air correction contract failed scenario="+scenario+" "+JsonUtility.ToJson(result));if(++scenario<(contract?64:40))Setup();else{File.WriteAllText(Path.Combine(F2DrivingDiagnostics.Output,"angles.json"),JsonUtility.ToJson(report,true));File.WriteAllText(Path.Combine(F2DrivingDiagnostics.Output,"result.txt"),contract?"AIR_CORRECTION_CONTRACT_OK cases=64 themes=2 ramps=8 speeds=2 headings=2 offsets=2\n":"F2_ANGLE_COLLECTION_DONE cases=40; diagnostic outcomes are not acceptance\n");EditorApplication.isPlaying=false;}}
 }
 [DefaultExecutionOrder(-100)] public sealed class F2CollisionDriver:MonoBehaviour {
  MagneticVehicle car;GameObject root,wall;int ticks;bool contact;long stopped;
  static void Set(MagneticVehicle c,string field,object value)=>typeof(MagneticVehicle).GetField(field,BindingFlags.NonPublic|BindingFlags.Instance).SetValue(c,value);
  void Start(){try{gameObject.AddComponent<RacePhysicsStepper>();root=new GameObject("collision lifecycle");var road=new GameObject("road");road.transform.SetParent(root.transform);var track=road.AddComponent<TrackBuilder>();track.Build(new TrackRoute(RoadVolumeChecks.FlatRoad()));var obj=new GameObject("collision pilot");obj.transform.SetParent(root.transform);car=obj.AddComponent<MagneticVehicle>();car.Initialize(track,0,Color.cyan,ReleaseBalance.Parse(Resources.Load<TextAsset>("balance-config").text),true);car.ResetAt(100);car.Body.position=car.Frame.position+car.Frame.normal*4;car.Body.linearVelocity=car.Frame.tangent*80;car.transform.position=car.Body.position;Set(car,"activeJump",new Procedural.Jump{id="collision",rampStartIndex=10,launchIndex=11,landingEndIndex=50,ballisticLandingEndIndex=50});Set(car,"airSteeringNormal",car.Frame.normal);Set(car,"flightStarted",Time.time);wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.transform.SetParent(root.transform);wall.transform.position=car.Body.position+car.Frame.tangent*2.45f;wall.transform.rotation=car.Frame.Rotation;wall.transform.localScale=new Vector3(10,10,.4f);car.ContactObserved+=c=>contact=true;Physics.SyncTransforms();}catch(Exception e){F2DrivingDiagnostics.Fail(e);}}
  void FixedUpdate(){try{if(car==null)return;car.PrepareProjection();car.SetRaceContext(true,1,1,ticks*.01);car.SetInput(new DrivingInput{steer=.5f});ticks++;
   if(ticks==2){if(!contact||car.AirSteeringSteps<=0||car.AirSteeringSteps>=8||car.AirSteeringActive)throw new Exception("Native contact cancellation: contact="+contact+" steps="+car.AirSteeringSteps);stopped=car.AirSteeringSteps;UnityEngine.Object.DestroyImmediate(wall);Physics.SyncTransforms();}
   if(ticks==3){if(car.AirSteeringSteps!=stopped)throw new Exception("Collision rearmed air control");
    car.ResetAt(100);car.Body.position=car.Frame.position+car.Frame.normal*4;car.Body.linearVelocity=car.Frame.tangent*80;car.transform.position=car.Body.position;Physics.SyncTransforms();Set(car,"activeJump",new Procedural.Jump{id="disable",landingEndIndex=50,ballisticLandingEndIndex=50});Set(car,"airSteeringNormal",car.Frame.normal);Set(car,"flightStarted",Time.time);car.SetInput(new DrivingInput{steer=.5f});typeof(MagneticVehicle).GetMethod("FixedUpdate",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(car,null);if(!car.AirSteeringActive)throw new Exception("Disable fixture did not arm");car.enabled=false;if(car.AirSteeringActive)throw new Exception("Actual PlayMode disable did not cancel air force");
    File.WriteAllText(Path.Combine(F2DrivingDiagnostics.Output,"collision.txt"),"AIR_COLLISION_NATIVE_OK stepsBeforeImpact="+stopped+" remainingSubstepsRevoked=true nextTickBlocked=true actualDisableCancels=true\n");UnityEngine.Debug.Log("AIR_COLLISION_NATIVE_OK stepsBeforeImpact="+stopped);car=null;EditorApplication.isPlaying=false;}
  }catch(Exception e){F2DrivingDiagnostics.Fail(e);}}
 }

}
